### ISSUE TITLE
Fine-tuned generic Yelp checkpoint missing

### ISSUE THREAD

**Issue by avshalomman** [amazon-science/adasum#5]
Hi again (I closed my previous issue because I made a mistake).
The yelp generic fine-tuned checkpoint link is broken:
https://abrazinskas.s3.eu-west-1.amazonaws.com/downloads/projects/adasum/artifacts/yelp/generic/checkpoint.pt
I need to run your model for research purposes, is there any chance you could provide the checkpoint?

Thanks a lot!

**Comment by markusdr** [comment]
Thanks for raising this issue. The path has been fixed now.
