### ISSUE TITLE
The termination of Amazon's unsupervised dataset

### ISSUE THREAD

**Issue by Zypressen021** [amazon-science/adasum#6]
Thanks for adasum.

I would like to run this model.
However, Amazon's unsupervised dataset has been updated and the version of the dataset you used is no longer available. (This dataset is linked at the beginning of "adasum/preprocessing/README.md")
This makes it impossible to reproduce the experiment, so I would appreciate it if you could provide the previous version of the raw datasets or the pre-processed leave-one-out datasets.

**Comment by abrazinskas** [comment]
Hello Zypressen021,

We have recently updated the scripts. So now it's possible to download older datasets from the previous project and pre-process them. This should help.

**Comment by Zypressen021** [comment]
Thank you for your response.
I appreciate that you have updated the scripts and made it possible to download older versions of the dataset and pre-process them. I will try to execute the scripts.
